### ISSUE TITLE
Unable to convert to CoreML model. Got Neptune-related error.

### ISSUE THREAD

**Issue by RahulBhalley** [bes-dev/MobileStyleGAN.pytorch#30]
Thank you so much for your work! I have some issue using it.

Running the following command.
```
python train.py --cfg configs/mobile_stylegan_ffhq.json --checkpoint_dir mobilestylegan_ffhq_v2.ckpt --export-model coreml --export-dir .
```

I get some error related to Neptune.
```
load mapping network...
load pretrained model: stylegan2_ffhq_config_f_mapping_network.ckpt...
Computing MD5: /tmp/stylegan2_ffhq_config_f_mapping_network.ckpt
MD5 matches: /tmp/stylegan2_ffhq_config_f_mapping_network.ckpt
load synthesis network...
load pretrained model: stylegan2_ffhq_config_f_synthesis_network.ckpt...
Computing MD5: /tmp/stylegan2_ffhq_config_f_synthesis_network.ckpt
MD5 matches: /tmp/stylegan2_ffhq_config_f_synthesis_network.ckpt
/usr/local/lib/python3.7/site-packages/torchvision/models/inception.py:83: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  ' due to scipy/scipy#11299), please set init_weights=True.', FutureWarning)
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    main(args)
  File "train.py", line 21, in main
    logger = build_logger(cfg.logger)
  File "train.py", line 12, in build_logger
    **cfg.params
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/loggers/neptune.py", line 270, in __init__
    self._verify_input_arguments(api_key, project, name, run, neptune_run_kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/loggers/neptune.py", line 358, in _verify_input_arguments
    raise ValueError(legacy_kwargs_msg.format(legacy_kwargs=used_legacy_kwargs))
ValueError: Following kwargs are deprecated: ['offline_mode', 'project_name', 'experiment_name'].
If you are looking for the Neptune logger using legacy Python API, it's still available as part of neptune-contrib package:
  - https://docs-legacy.neptune.ai/integrations/pytorch_lightning.html
The NeptuneLogger was re-written to use the neptune.new Python API
  - https://neptune.ai/blog/neptune-new
  - https://docs.neptune.ai/integrations-and-supported-tools/model-training/pytorch-lightning
You should use arguments accepted by either NeptuneLogger.init() or neptune.init()
```

How can I fix this?

**Comment by RahulBhalley** [comment]
Okay, so I just bypassed the logger by commenting it and also commented other package version conflicting arguments for other classes and functions.
