### ISSUE TITLE
model_zoo.json need an update 

### ISSUE THREAD

**Issue by emreaniloguz** [bes-dev/MobileStyleGAN.pytorch#39]
While trying to run the demo on my local computer, I have used this line of code as stated in README

`python demo.py --cfg configs/mobile_stylegan_ffhq.json`

As a result, I got this error:

```
actual: c6a23e76375fbbf2d554e199718d73e1
expected: 8de24b4d08049c32dbec8beca5ed2074
Cached Downloading: /tmp/mobilestylegan_ffhq.ckpt
Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    main(args)
  File "demo.py", line 15, in main
    ckpt = model_zoo(args.ckpt)
  File "/home/syn1650/Desktop/mobilestyle/MobileStyleGAN.pytorch/core/model_zoo.py", line 8, in model_zoo
    ckpt = download_ckpt(**zoo[name])
  File "/home/syn1650/Desktop/mobilestyle/MobileStyleGAN.pytorch/core/utils.py", line 29, in download_ckpt
    gdown.cached_download(url, ckpt_path, md5=md5)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/gdown/cached_download.py", line 123, in cached_download
    download(url, temp_path, quiet=quiet, proxy=proxy, speed=speed)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/gdown/download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/syn1650/anaconda3/envs/comparison/lib/python3.7/site-packages/requests/models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
```

Then I changed to the following line:
```Python
 "mobilestylegan_ffhq.ckpt": {
        "url": "https://drive.google.com/uc?id=11Kja0XGE8liLb6R5slNZjF3j3v_6xydt",
        "name": "mobilestylegan_ffhq.ckpt",
        "md5": "8de24b4d08049c32dbec8beca5ed2074"
    }
}
```
to
```Python
  "mobilestylegan_ffhq.ckpt": {
        "url": "https://drive.google.com/uc?id=11Kja0XGE8liLb6R5slNZjF3j3v_6xydt",
        "name": "mobilestylegan_ffhq_v2.ckpt",
        "md5": "8de24b4d08049c32dbec8beca5ed2074"
    }
}
```
And it worked. 

Also, I have downloaded all the files manually. I think something wrong with the code or my PC. The code just downloads mapping_network.ckpt.

**Comment by bes-dev** [comment]
@emreaniloguz please, try to update gdown package in your python env
